---
- hosts: all
  become: true
  tasks:

  - name: update repo index
    ansible.builtin.apt:
       update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install  support for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repo index
    ansible.builtin.dnf:
       update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apache2 package
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install  support for php
    ansible.builtin.dnf:
      name: php
      state: latest
    when: ansible_distribution == "Rocky"
